# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

#theme
theme: jekyll-theme-architect

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "index.html"
      layout: default
      title: "RelMongo | Java relationship-enabled domain model persistence framework for MongoDB"
      source_url: "https://github.com/kaiso/relmongo"
      docs_url: "https://github.com/kaiso/relmongo/wiki"
      description: "RelMongo is a Java relationships mapping framework for MongoDB though annotations like OneToMany, OneToOne and ManyToOne as an alternative for DBRef allowing cascade operations and lazy loading. RelMongo uses Spring data mongodb and manual references to overcome DBRef limitations"
      keywords: "Java framework,Spring data mongodb,references,associatins,dbref,@OneToOne,@OneToMany,@ManyToOne,lazy loading,cascading"

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : true

  # Plugins
  plugins:
  - jekyll-sitemap
