# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

#theme
theme: jekyll-theme-architect

defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "index.html"
      layout: default
      title: "RelMongo | Java relationship-enabled domain model persistence framework for MongoDB"
      source_url: "https://github.com/kaiso/relmongo"
      docs_url: "https://github.com/kaiso/relmongo/wiki"
      description: "RelMongo is a Java persistence framework of MongoDB domain objects whose goal is to allow to map two-way relationships or references between MongoDB documents and collections. RelMongo provides annotations like OneToMany, OneToOne and ManyToOne as an alternative for DBRef and allows cascade operations and lazy loading of domain model objects. The MongoDB references are persisted as embedded documents containing the target document reference id like DBRefs. RelMongo uses Spring data mongodb and MongoDB manual references which make lookup stages work properly and overcomes DBRef limitations."
      keywords: "Java framework,Spring data mongodb dbref,Spring data mongodb @dbref,MongoDB references,MongoDB associatins,@OneToOne,@OneToMany,@ManyToOne,@DBRef,DBREF,mongodb lazy loading,mongodb cascading"

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : true

  # Plugins
  plugins:
  - jekyll-sitemap
